print("Enter amount of lemon juice (in cups):")
Lemon_Amount = float(input())
print("Enter amount of water (in cups):")
Water_Amount = float(input())
print("Enter amount of agave nectar (in cups):")
Nectar_Amount = float(input())
print("How many servings does this make?")
Servings = float(input())
print('\n')
print("Lemonade ingredients - yields", '{:.2f}'.format(Servings))
print('{:.2f}'.format(Lemon_Amount), "cups(s) lemon juice")
print('{:.2f}'.format(Water_Amount), "cup(s) water")
print('{:.2f}'.format(Nectar_Amount), "cup(s) agave nectar")
print("How many servings would you like to make?")
Asked_Servings = float(input())
Lemon_Amount = Lemon_Amount * (Asked_Servings/Servings)
Water_Amount = Water_Amount * (Asked_Servings/Servings)
Nectar_Amount = Nectar_Amount * (Asked_Servings/Servings)
print('\n')
print("Lemonade ingredients - yields", '{:.2f}'.format(Asked_Servings))
print('{:.2f}'.format(Lemon_Amount), "cup(s) lemon juice")
print('{:.2f}'.format(Water_Amount), "cup(s) water")
print('{:.2f}'.format(Nectar_Amount), "cup(s) agave nectar")
Lemon_Amount = Lemon_Amount /16
Water_Amount = Water_Amount /16
Nectar_Amount = Nectar_Amount /16
print("Lemonade ingredients - yields", '{:.2f}'.format(Asked_Servings))
print('{:.2f}'.format(Lemon_Amount), "gallon(s) lemon juice")
print('{:.2f}'.format(Water_Amount), "gallon(s) water")
print('{:.2f}'.format(Nectar_Amount), "gallon(s) agave nectar")